config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :passengers
  
  namespace :api do
    resources :bookings, defaults: {format: 'json'}
    resources :passengers, defaults: {format: 'json'}
  end

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :passenger
end

app/controllers/api/bookings_controller.rb
class Api::BookingsController < ApplicationController
  http_basic_authenticate_with name: "nostra", password: "welcome1"
  before_action :fetch_booking, except: [:index, :create]
  skip_before_action :verify_authenticity_token
  
  def fetch_booking
    @booking = Booking.find(params[:id])
  end
  
  def index
    @bookings = Booking.all
    respond_to do |format|
      format.json {render json: @bookings}
    end
  end

  def show
    respond_to do |format|
      format.json {render json: @booking}
    end
  end
  
  def create
    @passenger = Passenger.where(phone: params[:passenger_phone]).first
    if @passenger != nil && @passenger.is_authenticated?(params[:passenger_password])
      @booking = Booking.new(booking_params)
      @booking.passenger = @passenger
      respond_to do |format|
        if @booking.save 
          DriverAssignmentWorker.perform_async(@booking.id)
          format.json {render json: @booking, status: :created}
        else
          format.json {render json: @booking.errors, status: :unprocessable_entity}
        end
      end
    else
      response = {status: "ERROR: Wrong phone number or password!"}
      respond_to do |format|
        format.json {render json: response}
      end
    end
  end
  
  def update
    respond_to do |format|
      if @booking.update_attributes(booking_params)
        format.json {head :no_content, status: :ok}
      else
        format.json {render json: @booking.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @booking.destroy
        format.json {head :no_content, status: :ok}
      else
        format.json {render json: @booking.errors, status: :unprocessable_entity}
      end
    end
  end
  
  private
  
  def booking_params
    params.require(:booking).permit(:booking_time, :pickup_time, :pickup_latitude, :pickup_longitude, :dropoff_latitude, :dropoff_longitude, :estimated_fare, :estimated_distance, :promo_code, :driver_tip, :driver_name, :driver_phone) if params[:booking]
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:booking_time, :pickup_time, :pickup_latitude, :pickup_longitude, :dropoff_latitude, :dropoff_longitude, :estimated_fare, :estimated_distance, :promo_code, :driver_tip, :driver_name, :driver_phone)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :booking_time %><br>
    <%= f.datetime_select :booking_time %>
  </div>
  <div class="field">
    <%= f.label :pickup_time %><br>
    <%= f.datetime_select :pickup_time %>
  </div>
  <div class="field">
    <%= f.label :pickup_latitude %><br>
    <%= f.text_field :pickup_latitude %>
  </div>
  <div class="field">
    <%= f.label :pickup_longitude %><br>
    <%= f.text_field :pickup_longitude %>
  </div>
  <div class="field">
    <%= f.label :dropoff_latitude %><br>
    <%= f.text_field :dropoff_latitude %>
  </div>
  <div class="field">
    <%= f.label :dropoff_longitude %><br>
    <%= f.text_field :dropoff_longitude %>
  </div>
  <div class="field">
    <%= f.label :estimated_fare %><br>
    <%= f.number_field :estimated_fare %>
  </div>
  <div class="field">
    <%= f.label :estimated_distance %><br>
    <%= f.text_field :estimated_distance %>
  </div>
  <div class="field">
    <%= f.label :promo_code %><br>
    <%= f.text_field :promo_code %>
  </div>
  <div class="field">
    <%= f.label :driver_tip %><br>
    <%= f.number_field :driver_tip %>
  </div>
  <div class="field">
    <%= f.label :driver_name %><br>
    <%= f.text_field :driver_name %>
  </div>
  <div class="field">
    <%= f.label :driver_phone %><br>
    <%= f.text_field :driver_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <thead>
    <tr>
      <th>Booking time</th>
      <th>Pickup time</th>
      <th>Pickup latitude</th>
      <th>Pickup longitude</th>
      <th>Dropoff latitude</th>
      <th>Dropoff longitude</th>
      <th>Estimated fare</th>
      <th>Estimated distance</th>
      <th>Promo code</th>
      <th>Driver tip</th>
      <th>Driver name</th>
      <th>Driver phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.booking_time %></td>
        <td><%= booking.pickup_time %></td>
        <td><%= booking.pickup_latitude %></td>
        <td><%= booking.pickup_longitude %></td>
        <td><%= booking.dropoff_latitude %></td>
        <td><%= booking.dropoff_longitude %></td>
        <td><%= booking.estimated_fare %></td>
        <td><%= booking.estimated_distance %></td>
        <td><%= booking.promo_code %></td>
        <td><%= booking.driver_tip %></td>
        <td><%= booking.driver_name %></td>
        <td><%= booking.driver_phone %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Booking time:</strong>
  <%= @booking.booking_time %>
</p>

<p>
  <strong>Pickup time:</strong>
  <%= @booking.pickup_time %>
</p>

<p>
  <strong>Pickup latitude:</strong>
  <%= @booking.pickup_latitude %>
</p>

<p>
  <strong>Pickup longitude:</strong>
  <%= @booking.pickup_longitude %>
</p>

<p>
  <strong>Dropoff latitude:</strong>
  <%= @booking.dropoff_latitude %>
</p>

<p>
  <strong>Dropoff longitude:</strong>
  <%= @booking.dropoff_longitude %>
</p>

<p>
  <strong>Estimated fare:</strong>
  <%= @booking.estimated_fare %>
</p>

<p>
  <strong>Estimated distance:</strong>
  <%= @booking.estimated_distance %>
</p>

<p>
  <strong>Promo code:</strong>
  <%= @booking.promo_code %>
</p>

<p>
  <strong>Driver tip:</strong>
  <%= @booking.driver_tip %>
</p>

<p>
  <strong>Driver name:</strong>
  <%= @booking.driver_name %>
</p>

<p>
  <strong>Driver phone:</strong>
  <%= @booking.driver_phone %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>