config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  resources :passengers
  
  namespace :api do
    resources :bookings, defaults: {format: 'json'}
    resources :passengers, defaults: {format: 'json'}
  end

end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  validates :name, :email, :phone, presence: true
  validates :email, :phone, uniqueness: true
  
  has_many :bookings
  
  def generate_password
    generated_password = Digest::SHA1.hexdigest(self.phone)
    self.password_hash = Digest::SHA1.hexdigest(generated_password)
    return generated_password
  end
  
  def is_authenticated?(passenger_password)
    return self.password_hash == (Digest::SHA1.hexdigest(passenger_password))
  end
end

app/controllers/api/passengers_controller.rb
class Api::PassengersController < ApplicationController
  http_basic_authenticate_with name: "nostra", password: "welcome1"
  before_action :fetch_passenger, except: [:index, :create]
  skip_before_action :verify_authenticity_token
  
  def fetch_passenger
    @passenger = Passenger.find(params[:id])
  end
  
  def index
    @passengers = Passenger.all
    respond_to do |format|
      format.json {render json: @passengers}
    end
  end

  def show
    respond_to do |format|
      format.json {render json: @passenger}
    end
  end

  def create
    @passenger = Passenger.new(passenger_params)
    generated_password = @passenger.generate_password
    response = {name: @passenger.name, email: @passenger.email, phone: @passenger.phone, generated_password: generated_password}
    respond_to do |format|
      if @passenger.save
        format.json {render json: response, status: :created}
        puts "\n\nNOTIFICATION: An email is sent to #{@passenger.email} with the generated password #{generated_password}\n\n"
      else
        format.json {render json: @passenger.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @passenger.update_attributes(passenger_params)
        format.json {head :no_content, status: :ok}
      else
        format.json {render json: @passenger.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    respond_to do |format|
      if @passenger.destroy
        format.json {head :no_content, status: :ok}
      else
        format.json {render json: @passenger.errors, status: :unprocessable_entity}
      end
    end
  end
  
  private
  
  def passenger_params
    params.require(:passenger).permit(:name, :email, :phone, :password_hash) if params[:passenger]
  end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  # POST /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)

    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_params
      params.require(:passenger).permit(:name, :email, :phone, :password_hash)
    end
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/views/passengers/_form.html.erb
<%= form_for(@passenger) do |f| %>
  <% if @passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
      <% @passenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :password_hash %><br>
    <%= f.text_field :password_hash %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passengers/edit.html.erb
<h1>Editing passenger</h1>

<%= render 'form' %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

app/views/passengers/index.html.erb
<h1>Listing passengers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Password hash</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.name %></td>
        <td><%= passenger.email %></td>
        <td><%= passenger.phone %></td>
        <td><%= passenger.password_hash %></td>
        <td><%= link_to 'Show', passenger %></td>
        <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
        <td><%= link_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger', new_passenger_path %>

app/views/passengers/new.html.erb
<h1>New passenger</h1>

<%= render 'form' %>

<%= link_to 'Back', passengers_path %>

app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @passenger.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @passenger.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @passenger.phone %>
</p>

<p>
  <strong>Password hash:</strong>
  <%= @passenger.password_hash %>
</p>

<%= link_to 'Edit', edit_passenger_path(@passenger) %> |
<%= link_to 'Back', passengers_path %>